############################
## CHANGE THESE
############################

baseURL: 'https://roran60.com'
title: 'Roran60'

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


