############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: Blog
  url: /blog/
  weight: 20
- name: Search
  url: https://search.roran60.com/
  weight: 30
